# Generated by Django 4.0 on 2022-04-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0002_productsincart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsInCart',
            new_name='ProductInCart',
        ),
    ]
